/**
 * TheCoin Broker
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PurchaseRequest model module.
* @module model/PurchaseRequest
* @version 0.0.1
*/
export default class PurchaseRequest {
    /**
    * Constructs a new <code>PurchaseRequest</code>.
    * @alias module:model/PurchaseRequest
    * @class
    * @param userData {String} 
    * @param fiatAmount {Number} 
    * @param timeStamp {Number} 
    */

    constructor(userData, fiatAmount, timeStamp) {
        

        
        

        this['userData'] = userData;this['fiatAmount'] = fiatAmount;this['timeStamp'] = timeStamp;

        
    }

    /**
    * Constructs a <code>PurchaseRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PurchaseRequest} obj Optional instance to populate.
    * @return {module:model/PurchaseRequest} The populated <code>PurchaseRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PurchaseRequest();

            
            
            

            if (data.hasOwnProperty('userData')) {
                obj['userData'] = ApiClient.convertToType(data['userData'], 'String');
            }
            if (data.hasOwnProperty('userAccount')) {
                obj['userAccount'] = ApiClient.convertToType(data['userAccount'], 'String');
            }
            if (data.hasOwnProperty('fiatAmount')) {
                obj['fiatAmount'] = ApiClient.convertToType(data['fiatAmount'], 'Number');
            }
            if (data.hasOwnProperty('timeStamp')) {
                obj['timeStamp'] = ApiClient.convertToType(data['timeStamp'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} userData
    */
    userData = undefined;
    /**
    * @member {String} userAccount
    */
    userAccount = undefined;
    /**
    * @member {Number} fiatAmount
    */
    fiatAmount = undefined;
    /**
    * @member {Number} timeStamp
    */
    timeStamp = undefined;








}


