/**
 * TheCoin Broker
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SellRequest model module.
* @module model/SellRequest
* @version 0.0.1
*/
export default class SellRequest {
    /**
    * Constructs a new <code>SellRequest</code>.
    * @alias module:model/SellRequest
    * @class
    * @param transactionHash {String} 
    * @param timestamp {Number} 
    * @param userData {String} 
    */

    constructor(transactionHash, timestamp, userData) {
        

        
        

        this['transactionHash'] = transactionHash;this['timestamp'] = timestamp;this['userData'] = userData;

        
    }

    /**
    * Constructs a <code>SellRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SellRequest} obj Optional instance to populate.
    * @return {module:model/SellRequest} The populated <code>SellRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SellRequest();

            
            
            

            if (data.hasOwnProperty('transactionHash')) {
                obj['transactionHash'] = ApiClient.convertToType(data['transactionHash'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('userData')) {
                obj['userData'] = ApiClient.convertToType(data['userData'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} transactionHash
    */
    transactionHash = undefined;
    /**
    * @member {Number} timestamp
    */
    timestamp = undefined;
    /**
    * @member {String} userData
    */
    userData = undefined;








}


