/**
 * TheCoin Broker
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import SellRequest from './SellRequest';





/**
* The SellRequestSigned model module.
* @module model/SellRequestSigned
* @version 0.0.1
*/
export default class SellRequestSigned {
    /**
    * Constructs a new <code>SellRequestSigned</code>.
    * @alias module:model/SellRequestSigned
    * @class
    * @param request {module:model/SellRequest} 
    * @param signature {String} 
    */

    constructor(request, signature) {
        

        
        

        this['request'] = request;this['signature'] = signature;

        
    }

    /**
    * Constructs a <code>SellRequestSigned</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SellRequestSigned} obj Optional instance to populate.
    * @return {module:model/SellRequestSigned} The populated <code>SellRequestSigned</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SellRequestSigned();

            
            
            

            if (data.hasOwnProperty('request')) {
                obj['request'] = SellRequest.constructFromObject(data['request']);
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/SellRequest} request
    */
    request = undefined;
    /**
    * @member {String} signature
    */
    signature = undefined;








}


