/**
 * TheCoin Broker
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import TapCapHistoryResponse from './TapCapHistoryResponse';





/**
* The TapCapHistoryResponseSigned model module.
* @module model/TapCapHistoryResponseSigned
* @version 0.0.1
*/
export default class TapCapHistoryResponseSigned {
    /**
    * Constructs a new <code>TapCapHistoryResponseSigned</code>.
    * @alias module:model/TapCapHistoryResponseSigned
    * @class
    * @param response {module:model/TapCapHistoryResponse} 
    * @param signature {String} 
    */

    constructor(response, signature) {
        

        
        

        this['response'] = response;this['signature'] = signature;

        
    }

    /**
    * Constructs a <code>TapCapHistoryResponseSigned</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TapCapHistoryResponseSigned} obj Optional instance to populate.
    * @return {module:model/TapCapHistoryResponseSigned} The populated <code>TapCapHistoryResponseSigned</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TapCapHistoryResponseSigned();

            
            
            

            if (data.hasOwnProperty('response')) {
                obj['response'] = TapCapHistoryResponse.constructFromObject(data['response']);
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/TapCapHistoryResponse} response
    */
    response = undefined;
    /**
    * @member {String} signature
    */
    signature = undefined;








}


