/**
 * TheCoin Broker
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TapCapQueryRequest model module.
* @module model/TapCapQueryRequest
* @version 0.0.1
*/
export default class TapCapQueryRequest {
    /**
    * Constructs a new <code>TapCapQueryRequest</code>.
    * @alias module:model/TapCapQueryRequest
    * @class
    * @param timestamp {Number} 
    * @param random {String} 
    * @param userAccount {String} 
    * @param signature {String} 
    */

    constructor(timestamp, random, userAccount, signature) {
        

        
        

        this['timestamp'] = timestamp;this['random'] = random;this['userAccount'] = userAccount;this['signature'] = signature;

        
    }

    /**
    * Constructs a <code>TapCapQueryRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TapCapQueryRequest} obj Optional instance to populate.
    * @return {module:model/TapCapQueryRequest} The populated <code>TapCapQueryRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TapCapQueryRequest();

            
            
            

            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('random')) {
                obj['random'] = ApiClient.convertToType(data['random'], 'String');
            }
            if (data.hasOwnProperty('userAccount')) {
                obj['userAccount'] = ApiClient.convertToType(data['userAccount'], 'String');
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} timestamp
    */
    timestamp = undefined;
    /**
    * @member {String} random
    */
    random = undefined;
    /**
    * @member {String} userAccount
    */
    userAccount = undefined;
    /**
    * @member {String} signature
    */
    signature = undefined;








}


