/**
 * TheCoin Broker
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 0.0.1
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import TapCapTransaction from './TapCapTransaction';





/**
* The TapCapHistoryResponse model module.
* @module model/TapCapHistoryResponse
* @version 0.0.1
*/
export default class TapCapHistoryResponse {
    /**
    * Constructs a new <code>TapCapHistoryResponse</code>.
    * @alias module:model/TapCapHistoryResponse
    * @class
    * @param history {Array.<module:model/TapCapTransaction>} 
    */

    constructor(history) {
        

        
        

        this['history'] = history;

        
    }

    /**
    * Constructs a <code>TapCapHistoryResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TapCapHistoryResponse} obj Optional instance to populate.
    * @return {module:model/TapCapHistoryResponse} The populated <code>TapCapHistoryResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TapCapHistoryResponse();

            
            
            

            if (data.hasOwnProperty('history')) {
                obj['history'] = ApiClient.convertToType(data['history'], [TapCapTransaction]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/TapCapTransaction>} history
    */
    history = undefined;








}


