/**
 * TheCoin Broker
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 1.0.0
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import SellResponse from './SellResponse';





/**
* The SellResponseSigned model module.
* @module model/SellResponseSigned
* @version 1.0.0
*/
export default class SellResponseSigned {
    /**
    * Constructs a new <code>SellResponseSigned</code>.
    * @alias module:model/SellResponseSigned
    * @class
    * @param response {module:model/SellResponse} 
    * @param signature {String} 
    */

    constructor(response, signature) {
        

        
        

        this['response'] = response;this['signature'] = signature;

        
    }

    /**
    * Constructs a <code>SellResponseSigned</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SellResponseSigned} obj Optional instance to populate.
    * @return {module:model/SellResponseSigned} The populated <code>SellResponseSigned</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SellResponseSigned();

            
            
            

            if (data.hasOwnProperty('response')) {
                obj['response'] = SellResponse.constructFromObject(data['response']);
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/SellResponse} response
    */
    response = undefined;
    /**
    * @member {String} signature
    */
    signature = undefined;








}


