/**
 * TheCoin Broker
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 1.0.0
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TapCapHistoryRequest model module.
* @module model/TapCapHistoryRequest
* @version 1.0.0
*/
export default class TapCapHistoryRequest {
    /**
    * Constructs a new <code>TapCapHistoryRequest</code>.
    * @alias module:model/TapCapHistoryRequest
    * @class
    * @param fromTimestamp {Number} 
    * @param untilTimestamp {Number} 
    * @param userAccount {String} 
    * @param random {String} 
    * @param signature {String} 
    */

    constructor(fromTimestamp, untilTimestamp, userAccount, random, signature) {
        

        
        

        this['fromTimestamp'] = fromTimestamp;this['untilTimestamp'] = untilTimestamp;this['userAccount'] = userAccount;this['random'] = random;this['signature'] = signature;

        
    }

    /**
    * Constructs a <code>TapCapHistoryRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TapCapHistoryRequest} obj Optional instance to populate.
    * @return {module:model/TapCapHistoryRequest} The populated <code>TapCapHistoryRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TapCapHistoryRequest();

            
            
            

            if (data.hasOwnProperty('fromTimestamp')) {
                obj['fromTimestamp'] = ApiClient.convertToType(data['fromTimestamp'], 'Number');
            }
            if (data.hasOwnProperty('untilTimestamp')) {
                obj['untilTimestamp'] = ApiClient.convertToType(data['untilTimestamp'], 'Number');
            }
            if (data.hasOwnProperty('userAccount')) {
                obj['userAccount'] = ApiClient.convertToType(data['userAccount'], 'String');
            }
            if (data.hasOwnProperty('random')) {
                obj['random'] = ApiClient.convertToType(data['random'], 'String');
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} fromTimestamp
    */
    fromTimestamp = undefined;
    /**
    * @member {Number} untilTimestamp
    */
    untilTimestamp = undefined;
    /**
    * @member {String} userAccount
    */
    userAccount = undefined;
    /**
    * @member {String} random
    */
    random = undefined;
    /**
    * @member {String} signature
    */
    signature = undefined;








}


