/**
 * TheCoin Broker
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 1.0.0
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TapCapTransaction model module.
* @module model/TapCapTransaction
* @version 1.0.0
*/
export default class TapCapTransaction {
    /**
    * Constructs a new <code>TapCapTransaction</code>.
    * @alias module:model/TapCapTransaction
    * @class
    * @param timestamp {Number} 
    * @param fiatAmount {Number} 
    * @param coinAmount {Number} 
    * @param merchantId {String} 
    */

    constructor(timestamp, fiatAmount, coinAmount, merchantId) {
        

        
        

        this['timestamp'] = timestamp;this['fiatAmount'] = fiatAmount;this['coinAmount'] = coinAmount;this['merchantId'] = merchantId;

        
    }

    /**
    * Constructs a <code>TapCapTransaction</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TapCapTransaction} obj Optional instance to populate.
    * @return {module:model/TapCapTransaction} The populated <code>TapCapTransaction</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TapCapTransaction();

            
            
            

            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Number');
            }
            if (data.hasOwnProperty('fiatAmount')) {
                obj['fiatAmount'] = ApiClient.convertToType(data['fiatAmount'], 'Number');
            }
            if (data.hasOwnProperty('coinAmount')) {
                obj['coinAmount'] = ApiClient.convertToType(data['coinAmount'], 'Number');
            }
            if (data.hasOwnProperty('merchantId')) {
                obj['merchantId'] = ApiClient.convertToType(data['merchantId'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} timestamp
    */
    timestamp = undefined;
    /**
    * @member {Number} fiatAmount
    */
    fiatAmount = undefined;
    /**
    * @member {Number} coinAmount
    */
    coinAmount = undefined;
    /**
    * @member {String} merchantId
    */
    merchantId = undefined;








}


