/**
 * TheCoin Broker
 * TheCoin broker services.  To be implemented allowing exchange of local currency to THESE
 *
 * OpenAPI spec version: 1.0.0
 * Contact: stephen.taylor.dev@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheCoinBroker);
  }
}(this, function(expect, TheCoinBroker) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TheCoinBroker.SellResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SellResponse', function() {
    it('should create an instance of SellResponse', function() {
      // uncomment below and update the code to test SellResponse
      //var instane = new TheCoinBroker.SellResponse();
      //expect(instance).to.be.a(TheCoinBroker.SellResponse);
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instane = new TheCoinBroker.SellResponse();
      //expect(instance).to.be();
    });

    it('should have the property coinAmount (base name: "coinAmount")', function() {
      // uncomment below and update the code to test the property coinAmount
      //var instane = new TheCoinBroker.SellResponse();
      //expect(instance).to.be();
    });

    it('should have the property fiatAmount (base name: "fiatAmount")', function() {
      // uncomment below and update the code to test the property fiatAmount
      //var instane = new TheCoinBroker.SellResponse();
      //expect(instance).to.be();
    });

  });

}));
